languages = {
    'en': {
        'greeting': 'Welcome to Your Nikki`s DiarieCS50',
        'greeting2': 'Keep track of your thoughts, activities, and memories in a beautiful way.',
        'home': 'Home',
        'dashboard': 'Go to Dashboard',
        'started': 'Get Started',
        'login': 'Log In',
        'start_writing': 'You don`t have any entries. Start writing!',
        'change_language': 'Language',
        'eng': 'English',
        'az': 'Azerbaijani',
        'register': 'Register',
        'dash': 'Dashboard',
        'about': 'About',
        'gallery': 'Gallery',
        'calendar': 'Calendar',
        'profile': 'Profile',
        'logout': 'Log out',
        'footer': '© 2024 Nikki`s DiarieCS50. All rights reserved.',
        'privacy': 'Privacy Policy',
        'terms': 'Terms of Service',
        'dash_entry': 'Your Diary Entries',
        'btn_add_new': 'Add New Entry',
        'btn_view': 'View',
        'btn_edit': 'Edit',
        'btn_delete': 'Delete',
        'delete_code': 'Are you sure you want to delete this entry?',
        'posted_on': 'Posted on',
        'no_tags': 'No tags',
        'edit_entry': 'Edit Entry',
        'entry_title': 'Entry Title',
        'entry_image': 'Entry Image (optional)',
        'current_image': 'Current Image',
        'content': 'Content',
        'tags': 'Tags (comma-separated)',
        'cancel': 'Cancel',
        'save_changes': 'Save Changes',
        'save': 'Add New',
        'title': 'Title',
        'date': 'Date and Time',
        'upload_image': 'Upload Image (optional)',
        'user_profile': 'User Profile',
        'username': 'Username',
        'email': 'Email',
        'name': 'Name',
        'surname': 'Surname',
        'country': 'Country',
        'city': 'City',
        'btn_edit_profile': 'Edit Profile',
        'btn_back_dashboard': 'Back to Dashboard',
        'profile_banner': 'Profile Banner',
        'profile_image': 'Profile Image',
        'email_add': 'Email Address',
        'your_name': 'Your Name',
        'your_surname': 'Your Surname',
        'your_country': 'Your Country',
        'your_city': 'Your City',
        'password': 'Password',
        'your_username': 'Your Username',
        'new_pass': 'New Password (leave blank to keep current password)',
        'confirm_pass': 'Confirm Password',
        'btn_update_profile': 'Update Profile',
        'login_account': 'Login to Your Account',
        'register_here': 'Register here',
        'dont_have_account': 'Don`t Have an Account?',
        'create_account': 'Create Your Account',
        'sign_up': 'Sign Up',
        'already_have_account': 'Already Have Account?',
        'login_here': 'Login here',
        'view_tags': 'Tags',
        'privacy': 'Privacy Policy',
        'last_updated': 'Last Updated',
        'intro': 'Nikki`s DiarieCS50 ("we", "our", or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website Nikki`s DiarieCS50 (the "Service"). Please read this policy carefully. If you disagree with the terms, do not use the Service.',
        'information_we_collect': 'Information We Collect',
        'types_of_information': 'We may collect the following types of information:',
        'personal_data': 'Personal Data: Information like your name, email address, phone number, and other identifiers.',
        'usage_data': 'Usage Data: Information about how you access and use the Service, including your IP address, browser type, and device information.',
        'how_we_use': 'How We Use Your Information',
        'use_purposes': 'We may use your information for the following purposes:',
        'operate_service': 'To operate and maintain the Service.',
        'customer_support': 'To provide customer support and respond to your requests.',
        'updates': 'To notify you about updates or changes to the Service.',
        'data_analysis': 'To analyze data and improve our Service.',
        'data_sharing': 'Data Sharing and Disclosure',
        'no_sharing': 'We do not share your personal information with third parties, except in the following cases:',
        'legal_obligations': 'To comply with legal obligations.',
        'protect_rights': 'To protect the rights and safety of our users.',
        'data_security': 'Data Security',
        'reasonable_steps': 'We take reasonable steps to protect your data, but no method of transmission over the internet is 100% secure. We cannot guarantee its absolute security.',
        'cookies': 'Cookies',
        'cookie_usage': 'We may use cookies to track your activity on the Service. You can manage your cookie preferences through your browser settings.',
        'your_rights': 'Your Rights',
        'access_update_delete': 'You have the right to access, update, or delete your personal data. To make a request, contact us at imnigarvalikhanova@gmail.com.',
        'changes_to_policy': 'Changes to This Policy',
        'notify_changes': 'We may update this Privacy Policy from time to time. We will notify you of changes by posting the updated policy on this page.',
        'contact_us': 'Contact Us',
        'questions_contact': 'If you have any questions or concerns about this Privacy Policy, please contact us at imnigarvalikhanova@gmail.com.',
        'terms_title': 'Terms of Service',
        'last_updated': 'Last Updated: 9/23/2024',
        'acceptance_of_terms': '1. Acceptance of Terms',
        'acceptance_text': 'By accessing the Service, you agree to these Terms of Service. If you do not agree, do not use the Service. These terms apply to all visitors, users, and others who access or use the Service.',
        'changes_to_terms': '2. Changes to Terms',
        'changes_text': 'We reserve the right to modify or replace these Terms at any time. Changes will be effective immediately upon posting to the website. It is your responsibility to review these Terms periodically for updates. Continued use of the Service after changes constitutes your acceptance.',
        'user_accounts': '3. User Accounts',
        'user_accounts_text': 'To access certain features of the Service, you may need to create an account. You must provide accurate and complete information. You are responsible for keeping your account details secure.',
        'user_conduct': '4. User Conduct',
        'user_conduct_text': 'By using our Service, you agree to follow these rules:',
        'user_conduct_bullets': [
            'No illegal activities.',
            'Do not upload harmful content.',
            'Do not interfere with the Service.'
        ],
        'user_conduct_termination': 'We may terminate your access if you violate these rules.',
        'intellectual_property': '5. Intellectual Property',
        'intellectual_property_text': 'All content on the website is protected by law. You cannot use it without permission.',
        'third_party_links': '6. Links to Third-Party Sites',
        'third_party_links_text': 'Our Service may link to other sites. We are not responsible for their content or practices.',
        'liability': '7. Limitation of Liability',
        'liability_text': 'We are not responsible for any damages resulting from your use of the Service.',
        'termination': '8. Termination',
        'termination_text': 'We may terminate your access to the Service at any time, for any reason, without notice.',
        'governing_law': '9. Governing Law',
        'governing_law_text': 'These Terms are governed by the laws of Republic of Azerbaijan.',
        'contact_info': '10. Contact Information',
        'contact_info_text': 'If you have any questions, contact us at imnigarvalikhanova@gmail.com.',
        'about_creator': 'About the Creator',
        'its_me': 'Hi, I`m Nigar, the creator of NikkiDiarieCS50. This platform is designed for those who wish to express themselves freely and document their personal journeys.',
        'welcome_about': 'Welcome to NikkiDiarieCS50',
        'welcome_about2': 'NikkiDiarieCS50 is not just a diary; it`s a digital companion designed to help you capture your thoughts, experiences, and memories in a user-friendly environment.',
        'our_mission': 'Our Mission',
        'about_features': 'Features',
        'our_vision': 'Our Vision',
        'about_contact': 'Contact',
        'our_mission_text': 'At NikkiDiarieCS50, we believe that everyone has a story worth sharing. Our mission is to create a seamless platform where you can document your life’s journey with ease and creativity. We aim to empower users to reflect on their experiences, grow personally, and connect with their memories over time.',
        'feature_text_1': 'Daily Diary Entries: Record your thoughts, experiences, and emotions each day. Our intuitive interface makes it easy to write and reflect.',
        'feature_text_2': 'Gallery Feature: Showcase your favorite moments! Our gallery feature allows you to upload and curate images that resonate with your experiences. Whether it`s snapshots from a vacation, a special event, or everyday moments that matter, you can keep them all in one place and revisit them whenever you like.',
        'feature_text_3': 'Calendar View: Visualize your entries over time with our calendar feature, allowing you to track your mood, habits, and milestones.',
        'feature_text_4': 'Customizable Dashboard: Manage your profile and diary entries with a comprehensive dashboard tailored to your needs.',
        'our_vision_text': 'We envision a world where everyone can cherish their memories, learn from their experiences, and grow as individuals. NikkiDiarieCS50 aspires to be the go-to platform for personal documentation, combining simplicity and functionality.',
        'about_contact_text': 'Become part of the NikkiDiarieCS50 community! Share your thoughts, connect with others, and explore the diverse stories that make us all unique. Your journey matters, and we’re here to support you every step of the way. Reach out to us at',
        'contact_text_mail': 'info@nikkidiariecs50.com',
        'our_location': 'Our Location',
        'sun': 'Sun',
        'mon': 'Mon',
        'tue': 'Tue',
        'wed': 'Wed',
        'thu': 'Thu',
        'fri': 'Fri',
        'sat': 'Sat',
        'jan': 'January',
        'feb': 'February',
        'mar': 'March',
        'apr': 'April',
        'may': 'May',
        'jun': 'June',
        'jul': 'July',
        'aug': 'August',
        'sep': 'September',
        'oct': 'October',
        'nov': 'November',
        'dec': 'December',
        'prev': 'Previous',
        'next': 'Next',
        'upload_image': 'Upload Image',
        'image_viewer': 'Image Viewer',
        'uploaded_on': 'Uploaded on',
        'back_gallery': 'Back to Gallery',
        'btn_delete_img': 'Delete Image',
    },
    'az': {
        'greeting': 'Nikki`s DiarieCS50`ə xoş gəlmisiniz',
        'greeting2': 'Fikirlərinizi, fəaliyyətlərinizi və xatirələrinizi gözəl şəkildə izləyin.',
        'home': 'Əsas',
        'dashboard': 'İdarə panelinə keçin',
        'started': 'Başlayın',
        'login': 'Daxil ol',
        'start_writing': 'Gündəliyinizdə heç bir qeyd yoxdur. Yazmağa başlayın!',
        'change_language': 'Dil',
        'eng': 'İngiliscə',
        'az': 'Azərbaycanca',
        'register': 'Qeydiyyat',
        'dash': 'Panel',
        'about': 'Haqqımızda',
        'gallery': 'Qalereya',
        'calendar': 'Təqvim',
        'profile': 'Profil',
        'logout': 'Çıxış',
        'footer': '© 2024 Nikki`s DiarieCS50. Bütün hüquqlar qorunur.',
        'privacy': 'Məxfilik Siyasəti',
        'terms': 'Xidmət Şərtləri',
        'dash_entry': 'Gündəlik qeydləriniz',
        'btn_add_new': 'Yeni Gündəlik Yarat',
        'btn_view': 'Bax',
        'btn_edit': 'Dəyİş',
        'btn_delete': 'Sİl',
        'delete_code': 'Bu günü silmək istədiyinizə əminsiniz?',
        'posted_on': 'Yaradılma tarixi',
        'no_tags': 'Teq yoxdur',
        'edit_entry': 'Gündəliyi dəyiş',
        'entry_title': 'Gündəlik başlığı',
        'entry_image': 'Gündəlik şəkli (istəyə bağlı)',
        'current_image': 'Cari Şəkil',
        'content': 'Məzmun',
        'tags': 'Teqlər (vergüllə ayrılmış)',
        'cancel': 'Ləğv et',
        'save_changes': 'Dəyişikliyi Yadda Saxla',
        'save': 'Yenisini Yarat',
        'title': 'Başlıq',
        'date': 'Zaman',
        'upload_image': 'Şəkil Yüklə (istəyə bağlı)',
        'user_profile': 'İstifadəçi Profili',
        'username': 'İstifadəçi Adı',
        'email': 'Elektron ünvanı',
        'name': 'Adı',
        'surname': 'Soyadı',
        'country': 'Ölkə',
        'city': 'Şəhər',
        'btn_edit_profile': 'Profili Dəyiş',
        'btn_back_dashboard': 'Panelə Geri Qayıt',
        'profile_banner': 'Profil Arxa Fonu',
        'profile_image': 'Profil Şəkli',
        'email_add': 'Elektron ünvanınız',
        'your_name': 'Adınız',
        'your_surname': 'Soyadınız',
        'your_country': 'Ölkəniz',
        'your_city': 'Şəhəriniz',
        'password': 'Şifrəniz',
        'your_username': 'İstifadəçi Adınız',
        'new_pass': 'Yeni Şifrə (cari şifrəni saxlamaq üçün boş buraxın)',
        'confirm_pass': 'Şifrəni doğrula',
        'btn_update_profile': 'Profili Yeniləyin',
        'login_account': 'Öz hesabınıza daxil olun',
        'register_here': 'Buradan qeydiyyatdan keçin',
        'dont_have_account': 'Bir Hesabınız Yoxdur?',
        'create_account': 'Hesabınızı Yaradın',
        'sign_up': 'Hesab Yarat',
        'already_have_account': 'Artıq Hesabınız Var?',
        'login_here': 'Buradan daxil olun',
        'view_tags': 'Teqlər',
        'privacy': 'Məxfilik Siyasəti',
        'last_updated': 'Son Yenilənmə',
        'intro': 'Nikki`s DiarieCS50 ("biz", "bizim" və ya "bizə") məxfiliyinizi qorumağa sadiqdir. Bu Məxfilik Siyasəti, vebsaytımızı ziyarət etdiyiniz zaman məlumatlarınızı necə toplayır, istifadə edir, açıqlayır və qoruduğumuzu izah edir Nikki`s DiarieCS50 (xidmət). Zəhmət olmasa, bu siyasəti diqqətlə oxuyun. Şərtlərlə razı deyilsinizsə, xidmətdən istifadə etməyin.',
        'information_we_collect': 'Topladığımız Məlumatlar',
        'types_of_information': 'Biz aşağıdakı növ məlumatları toplaya bilərik:',
        'personal_data': 'Şəxsi Məlumat: Adınız, e-poçt ünvanınız, telefon nömrəniz və digər identifikatorlar.',
        'usage_data': 'İstifadə Məlumatı: Xidmətə necə daxil olduğunuz və onu necə istifadə etdiyiniz barədə məlumatlar, o cümlədən IP ünvanınız, brauzer növü və cihaz məlumatları.',
        'how_we_use': 'Məlumatlarınızı Necə İstifadə Edirik',
        'use_purposes': 'Məlumatlarınızı aşağıdakı məqsədlər üçün istifadə edə bilərik:',
        'operate_service': 'Xidmətin işləməsi və saxlanması.',
        'customer_support': 'Müştəri dəstəyi vermək və sorğularınıza cavab vermək.',
        'updates': 'Xidmətə dair yeniliklər və dəyişikliklər haqqında sizi məlumatlandırmaq.',
        'data_analysis': 'Məlumatları təhlil etmək və xidmətimizi yaxşılaşdırmaq.',
        'data_sharing': 'Məlumatların Paylaşılması və Açıqlanması',
        'no_sharing': 'Biz şəxsi məlumatlarınızı üçüncü tərəflərlə paylaşmırıq, yalnız aşağıdakı hallarda:',
        'legal_obligations': 'Hüquqi öhdəliklərə riayət etmək.',
        'protect_rights': 'İstifadəçilərimizin hüquq və təhlükəsizliyini qorumaq.',
        'data_security': 'Məlumatların Təhlükəsizliyi',
        'reasonable_steps': 'Məlumatlarınızı qorumaq üçün məqbul addımlar atırıq, lakin internet üzərindən ötürülən hər hansı bir metod 100% təhlükəsiz deyil. Biz onun tam təhlükəsizliyini təmin edə bilmirik.',
        'cookies': 'Çərəzlər',
        'cookie_usage': 'Xidmət üzərində fəaliyyətinizi izləmək üçün çərəzlərdən istifadə edə bilərik. Brauzer ayarlarınız vasitəsilə çərəz seçimlərinizi idarə edə bilərsiniz.',
        'your_rights': 'Sizin Hüquqlarınız',
        'access_update_delete': 'Şəxsi məlumatlarınıza giriş, yeniləmə və ya silmək hüququna maliksiniz. Sorğu etmək üçün bizimlə əlaqə saxlayın imnigarvalikhanova@gmail.com.',
        'changes_to_policy': 'Bu Siyasətdə Dəyişikliklər',
        'notify_changes': 'Biz bu Məxfilik Siyasətini zaman-zaman yeniləyə bilərik. Dəyişikliklər barədə sizi bu səhifədəki yenilənmiş siyasəti dərc etməklə məlumatlandıracağıq.',
        'contact_us': 'Bizimlə Əlaqə',
        'questions_contact': 'Bu Məxfilik Siyasəti ilə bağlı suallarınız və ya narahatlıqlarınız varsa, bizimlə əlaqə saxlayın imnigarvalikhanova@gmail.com.',
        'terms_title': 'Xidmət Şərtləri',
        'last_updated': 'Son Yenilənmə: 23/09/2024',
        'acceptance_of_terms': '1. Şərtlərin Qəbulu',
        'acceptance_text': 'Xidmətə daxil olaraq, bu Şərtləri qəbul edirsiniz. Əgər qəbul etmirsinizsə, xidmətdən istifadə etməyin. Bu şərtlər bütün istifadəçilərə aiddir.',
        'changes_to_terms': '2. Şərtlərin Dəyişdirilməsi',
        'changes_text': 'Biz bu Şərtləri hər zaman dəyişə bilərik. Dəyişikliklər vebsaytda yerləşdirildiyi andan qüvvəyə minir. Yenilənmiş şərtləri vaxtaşırı nəzərdən keçirmək sizin məsuliyyətinizdir.',
        'user_accounts': '3. İstifadəçi Hesabları',
        'user_accounts_text': 'Xidmətin bəzi xüsusiyyətlərindən istifadə etmək üçün hesab yaratmağınız tələb oluna bilər. Doğru məlumat verməyiniz tələb olunur və hesabınızın təhlükəsizliyindən siz cavabdehsiniz.',
        'user_conduct': '4. İstifadəçi Davranışı',
        'user_conduct_text': 'Xidmətimizdən istifadə edərkən, aşağıdakı qaydalara əməl etməlisiniz:',
        'user_conduct_bullets': [
            'Qanunsuz fəaliyyətlərə yol verməyin.',
            'Təhqiredici məzmun yükləməyin.',
            'Xidmətə müdaxilə etməyin.'
        ],
        'user_conduct_termination': 'Bu qaydaları pozsanız, girişiniz dayandırıla bilər.',
        'intellectual_property': '5. Əqli Mülkiyyət',
        'intellectual_property_text': 'Saytdakı bütün məzmun qanunla qorunur və icazəsiz istifadə edilə bilməz.',
        'third_party_links': '6. Üçüncü Tərəf Saytlara Keçidlər',
        'third_party_links_text': 'Xidmətimiz digər saytlara keçidlər təqdim edə bilər. Biz həmin saytların məzmununa görə məsuliyyət daşımırıq.',
        'liability': '7. Məsuliyyətin Məhdudlaşdırılması',
        'liability_text': 'Biz Xidmətin istifadəsi nəticəsində yaranan hər hansı zərərə görə məsuliyyət daşımırıq.',
        'termination': '8. Xidmətin Dayandırılması',
        'termination_text': 'Biz girişinizi istənilən vaxt, hər hansı səbəbdən dayandıra bilərik.',
        'governing_law': '9. Hüquqi Tənzimləmə',
        'governing_law_text': 'Bu Şərtlər Azərbaycan Respublikasının qanunları ilə tənzimlənir.',
        'contact_info': '10. Əlaqə Məlumatları',
        'contact_info_text': 'Suallarınız varsa, bizimlə imnigarvalikhanova@gmail.com vasitəsilə əlaqə saxlayın.',
        'about_creator': 'Səhifənin Yaradıcısı Haqqında',
        'its_me': 'Salam, mən Nigar, NikkiDiarieCS50-nin yaradıcısıyam. Bu platforma özünü sərbəst ifadə etmək və şəxsi səyahətlərini sənədləşdirmək istəyənlər üçün nəzərdə tutulub.',
        'welcome_about': 'NikkiDiarieCS50`ə xoş gəldiniz',
        'welcome_about2': 'NikkiDiarieCS50 sadəcə gündəlik deyil; bu, fikirlərinizi, təcrübələrinizi və xatirələrinizi istifadəçi dostu bir mühitdə tutmağınıza kömək etmək üçün nəzərdə tutulmuş rəqəmsal yoldaşdır.',
        'our_mission': 'Missiyamız',
        'about_features': 'Xüsusiyyətlər',
        'our_vision': 'Baxışımız',
        'about_contact': 'Əlaqə',
        'our_mission_text': 'NikkiDiarieCS50-də biz hər kəsin paylaşmağa dəyər hekayəsi olduğuna inanırıq. Missiyamız həyat səyahətinizi asanlıqla və yaradıcılıqla sənədləşdirə biləcəyiniz qüsursuz platforma yaratmaqdır. Biz istifadəçilərə öz təcrübələri üzərində düşünmək, şəxsi inkişaf etmək və zaman keçdikcə xatirələri ilə əlaqə saxlamaq imkanı vermək istəyirik.',
        'feature_text_1': 'Hərgün Gündəlik Girişləri: Hər gün düşüncələrinizi, təcrübələrinizi və duyğularınızı qeyd edin. Bizim intuitiv interfeysimiz yazmağı və əks etdirməyi asanlaşdırır.',
        'feature_text_2': 'Qalereya Xüsusiyyəti: Sevimli anlarınızı nümayiş etdirin! Qalereya xüsusiyyətimiz sizə təcrübələrinizlə rezonans doğuran şəkilləri yükləməyə və düzəltməyə imkan verir. İstər tətildən, istər xüsusi hadisədən, istərsə də vacib olan gündəlik anlardan kadrlar olsun, siz onların hamısını bir yerdə saxlaya və istədiyiniz zaman yenidən baxa bilərsiniz.',
        'feature_text_3': 'Təqvim Görünüşü: əhvalınızı, vərdişlərinizi və mərhələlərinizi izləməyə imkan verən təqvim xüsusiyyətimizlə qeydlərinizi zamanla vizuallaşdırın.',
        'feature_text_4': 'Fərdiləşdirilə bilən İdarə Paneli: Ehtiyaclarınıza uyğunlaşdırılmış hərtərəfli idarə paneli ilə profilinizi və gündəlik qeydlərinizi idarə edin.',
        'our_vision_text': 'Biz hər kəsin öz xatirələrini yaşaya biləcəyi, təcrübələrindən öyrənə biləcəyi və fərd kimi böyüyə biləcəyi bir dünya təsəvvür edirik. NikkiDiarieCS50 sadəlik və funksionallığı özündə birləşdirən şəxsi sənədlər üçün əsas platforma olmağa can atır.',
        'about_contact_text': 'NikkiDiarieCS50 icmasının bir hissəsi ol! Fikirlərinizi paylaşın, başqaları ilə əlaqə saxlayın və hamımızı unikal edən müxtəlif hekayələri araşdırın. Səyahətiniz vacibdir və biz sizə hər addımda dəstək olmaq üçün buradayıq. Bizimlə əlaqə saxlayın',
        'contact_text_mail': 'info@nikkidiariecs50.com',
        'our_location': 'Məkanımız',
        'sun': 'B',
        'mon': 'B.e.',
        'tue': 'Ç.a.',
        'wed': 'Ç',
        'thu': 'C.a.',
        'fri': 'C',
        'sat': 'Ş',
        'jan': 'Yanvar',
        'feb': 'Fevral',
        'mar': 'Mart',
        'apr': 'Aprel',
        'may': 'May',
        'jun': 'İyun',
        'jul': 'İyul',
        'aug': 'Avqust',
        'sep': 'Sentyabr',
        'oct': 'Oktyabr',
        'nov': 'Noyabr',
        'dec': 'Dekabr',
        'prev': 'Əvvəl',
        'next': 'Sonra',
        'upload_image': 'Şəkil Yüklə',
        'image_viewer': 'Şəklə Baxış',
        'uploaded_on': 'Yüklənilmə tarixi',
        'back_gallery': 'Qalereyaya Qayıt',
        'btn_delete_img': 'Şəkli Sil',
    }
}


def get_languages():
    return languages
